import React from "react"

export const Spinner = () => {
  return (
    <>
    
      {/* <? xml version = "1.0" encoding = "utf-8" ?> */}
      <svg xmlns="http://www.w3.org/2000/svg" style={{position: 'fixed', left:'45vw', bottom:'50%', }}>
        <g>
          <path d="M50 28A22 22 0 1 0 72 50.00000000000001" fill="none" stroke="#1d3f72" stroke-width="10"></path>
          <path d="M49 19L49 37L58 28L49 19" fill="#1d3f72"></path>
          <animateTransform attributeName="transform" type="rotate" repeatCount="indefinite" dur="0.6711409395973155s" values="0 50 50;360 50 50" keyTimes="0;1"></animateTransform>
        </g>
        {/* <!-- [ldio] generated by https://loading.io/ --> */}
      </svg>
    </>
  )
}